[FIX] Iso format for v3 is called twice
blockchain-certificates/cert-tools pull request #49
Opened 2021-04-25 10:28 UTC by flachica

2021-04-26 09:22 UTC, lemoustachiste commented on .travis.yml
>    - "3.6"
why removing the 2.7 version?

2021-04-26 09:23 UTC, lemoustachiste commented on cert_tools/helpers.py
> +    return datetime.now(timezone.utc).isoformat()[:-13]+'Z'
that looks good, now that I look at the other code, it was indeed a strange setup.

2021-04-26 09:24 UTC, lemoustachiste reviewed
@lparkerlm can you weigh in on the removal of python 2.7?

2021-04-26 19:52 UTC, flachica commented on .travis.yml
>    - "3.6"
To be able to pass the tests

2021-04-27 16:50 UTC, lemoustachiste requested changes
@flachica we had a discussion with @lparkerlm and as it stands, removing python 2.7 cannot be accepted as part of this PR. We need more time to flesh out the issue with this version, and decide if we maintain or remove support. 

In my opinion your code looks ok, and if it works with Python 3, then I think it's good enough for the current purpose. Python 2.7 issue has been lingering for a while, so we would need to take a proper look at it.

2021-07-21 08:54 UTC, antonellopasella commented
Updated without Python3 removal in https://github.com/blockchain-certificates/cert-tools/pull/51

2021-07-24 16:40 UTC, closed without merging